### ISSUE TITLE
iOS issue

### ISSUE THREAD

**Issue by Artmos** [Broxxar/NoMansScanner#2]
Hey Dan,

I love your videos, very educative, cool and straight to the point, they're great for someone like me just getting into shaders and effects.

I've been playing around with this shader, simplifying it a bit and trying to get it working on iOS. The effect looks great in the editor, however on iOS it has a really jagged outer edge. I don't know if it could be caused by the data type precision being lower on iOS. Do you have any insight into what could be causing this and maybe even ways to fix the problem?

![image](https://cloud.githubusercontent.com/assets/187554/18361488/44b8433c-7602-11e6-9c50-c9caa76fbc55.png)

**Comment by Broxxar** [comment]
Hey Artmos,

It definitely looks like a precision issue. You can try reducing the far clip plane. Unfortunately I haven't got access to an OSX device for testing and profiling at the moment.

An absolutely hacky way you could do this would be to render the scene again to a rendertexture, using a replacement shader that generates high precision depth values using EncodeFloatRG or EncodeFloatRGBA. That would be pretty taxing though so I'm not sure how an iPad would handle it.

In any case, please share your findings here, it would be very helpful :)

**Comment by Artmos** [comment]
So I finally got some time to experiment some more with this and I think I've found a solution.

It seems to be a problem with the precision of the depth texture on newer iOS devices, this is easily fixed by changing:

`sampler2D _CameraDepthTexture;`

to

`sampler2D_float _CameraDepthTexture;`

This is also described in this post: http://forum.unity3d.com/threads/ios-depth-texture-precision-solved.394684/

In my project I also removed the dependency on the GlobalFog image effect by adding the following to the Start method of our script:

`_camera.depthTextureMode = DepthTextureMode.Depth;`

**Comment by Broxxar** [comment]
Awesome work, I didn't realize the sampler2D would default to half or low precision on iOS. Strange behaviour. I wonder if that affects the precision of other image effects as well.

I'll commit a new version with the camera depth mode set in the scanner script, didn't catch that I left it out as it was on the fog script.

Thanks for your work debugging this. I'm sure many will appreciate this!
